webtalk_init -webtalk_dir /home/alexyh/Escritorio/Arqui/Arquitectura_TP3/Arquitectura_TP3/Arquitectura_TP3.sim/sim_1/behav/xsim/xsim.dir/test_bip_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 25 20:45:11 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "01a45b63-fb74-46bb-968c-bd5280047c2e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e2861177ce2843239e0962205fa027ce" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "50" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 19.1 Tessa" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3100.216 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.07_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "129292_KB" -context "xsim\\usage"
webtalk_transmit -clientid 141362705 -regid "" -xml /home/alexyh/Escritorio/Arqui/Arquitectura_TP3/Arquitectura_TP3/Arquitectura_TP3.sim/sim_1/behav/xsim/xsim.dir/test_bip_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/alexyh/Escritorio/Arqui/Arquitectura_TP3/Arquitectura_TP3/Arquitectura_TP3.sim/sim_1/behav/xsim/xsim.dir/test_bip_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/alexyh/Escritorio/Arqui/Arquitectura_TP3/Arquitectura_TP3/Arquitectura_TP3.sim/sim_1/behav/xsim/xsim.dir/test_bip_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
